export const DEFAULT_PVALS: number[] = [
  /* 0:  RANDOMNESS_MARGIN (~ noise)          */ 30,
  /* 1:  GAME_END_SCORE (+win/-loss)          */ 100000,
  /* 2:  KING_ONBOARD                         */ 20000,
  /* 3:  KING_THREATENED_BY_PIECE (*)         */ 0.3,
  /* 4:  KING_THREATENED_BUT_CAN_TAKE (*)     */ 0.8,
  /* 5:  HILL_CONTROL_COUNT                   */ 1000,
  /* 6:  PAWN_ON_HILL                         */ 600,
  /* 7:  PAWN_HILL_NO_KING                    */ 4000,
  /* 8:  CENTER_THREAT_COUNT                  */ 300,
  /* 9:  PIECE_BASE_COUNT                     */ 60,
  /* 10: PIECE_PAWN (*)                       */ 0.3,
  /* 11: PIECE_KNIGHT (*)                     */ 0.99,
  /* 12: PIECE_BISHOP (*)                     */ 0.7,
  /* 13: PIECE_ROOK (*)                       */ 0.6,
  /* 14: PIECE_UNPROTECTED_BY_PIECE (*)       */ 0.6,
  /* 15: PIECE_PROTECTED_BY_PIECE (*)         */ 0.8,
  /* 16: PIECE_BUNKERED_BY_PIECE (*)          */ 0.8,
  /* 17: PIECE_UNPROTECTED_BY_KING (*)        */ 0.2,
  /* 18: PIECE_PROTECTED_BY_KING (*)          */ 0.99,
  /* 19: PIECE_BUNKERED_BY_KING (*)           */ 0.99,
  /* 20: GAP1_ROOT_TOP4                       */ 10000,
  /* 21: GAP2_ROOT_TOP8                       */ 3000,
  /* 22: GAP_DEEP_PLIES                       */ 3000
];
